### ISSUE TITLE
data

### ISSUE THREAD

**Issue by Asmoody** [Ashargin/SC2AI#1]
hi
in the end of (run_local.py)
u save rewards.npy and net.h5
but if we want use that data for our agent again what must we do
i mean how can we import them to use in smartagent

**Comment by Ashargin** [comment]
Hello, a saved numpy array can be loaded with [numpy.load](https://numpy.org/doc/stable/reference/generated/numpy.load.html).
Similarly, a saved keras model can be loaded with [the keras load function](https://www.tensorflow.org/guide/keras/save_and_serialize#keras_h5_format).

**Comment by Asmoody** [comment]
could you add this code to  (run_local.py) too
ty
